import { DailyListenRepository } from '~~/server/repositories/dailyListen.repository';
import { UserRepository } from '~~/server/repositories/user.repository';
import type { UserWithAuthTokens } from '~~/server/services/user.service';
import { createTaggedLogger } from '~~/server/utils/logger';
import { PlaylistService } from './playlist.service';

const logger = createTaggedLogger('Service:SongOfDayPlaylist');

export class SongOfDayPlaylistService extends PlaylistService {
  constructor(
    private dailyListenRepo = new DailyListenRepository(),
    private userRepo = new UserRepository(),
  ) {
    super(logger);
  }

  /**
   * Updates the Song of the Day playlist with all favorite songs from the current year
   * @returns Playlist details or null if feature disabled or no favorites
   */
  async updateSongOfDayPlaylist(user: UserWithAuthTokens) {
    const { id: userId } = user;
    logger.info('Updating Song of the Day playlist', { userId });

    // Check if user has feature enabled
    const preferences = await this.userRepo.getPreferences(userId);
    if (!preferences?.createSongOfDayPlaylist) {
      logger.debug('Song of day playlist feature disabled for user', {
        userId,
      });
      return null;
    }

    const { spotifyClient, spotifyUserId } = await this.getSpotifyContext(user);

    const currentYear = new Date().getUTCFullYear();

    const favoriteSongs = await this.dailyListenRepo.getFavoriteSongsForYear(
      userId,
      currentYear,
    );

    logger.info('Found favorite songs for year', {
      userId,
      year: currentYear,
      count: favoriteSongs.length,
    });

    return await this.upsertSpotifyPlaylist(
      userId,
      spotifyUserId,
      spotifyClient,
      favoriteSongs.map((song) => `spotify:track:${song.favoriteSongId}`),
      {
        type: 'song_of_the_day',
        name: `DailySpin - Song of the Day ${currentYear}`,
        description: `Auto-generated by DailySpin - Your favorite songs from ${currentYear}`,
      },
    );
  }
}
