import type { SpotifyApi } from '@spotify/web-api-ts-sdk';
import { startOfDay } from 'date-fns';
import { FutureListenRepository } from '~~/server/repositories/futureListen.repository';
import type { UserWithAuthTokens } from '~~/server/services/user.service';
import { createTaggedLogger } from '~~/server/utils/logger';
import { PlaylistService } from './playlist.service';

const logger = createTaggedLogger('Service:TodaysAlbumPlaylist');

export class TodaysAlbumPlaylistService extends PlaylistService {
  constructor(private futureListenRepo = new FutureListenRepository()) {
    super(logger);
  }

  /**
   * Creates or updates the daily-spin playlist for today's scheduled album
   * @returns Playlist details or null if no album scheduled
   */
  async updateTodaysAlbumPlaylist(user: UserWithAuthTokens) {
    const { id: userId } = user;
    logger.info("Updating today's album playlist", { userId });

    // Get today's scheduled album
    const today = startOfDay(new Date());

    const futureListen = await this.futureListenRepo.getFutureListenByDate(
      userId,
      today,
    );

    if (!futureListen) {
      logger.debug('No album scheduled for today', {
        userId,
        date: today.toISOString(),
      });
      return null;
    }

    const { spotifyClient, spotifyUserId } = await this.getSpotifyContext(user);

    const { album } = futureListen;
    const artists = album.artists.map((a) => ({ name: a.artist.name }));

    logger.info('Found scheduled album', {
      userId,
      albumId: album.spotifyId,
      albumName: album.name,
    });

    // Fetch album tracks from Spotify
    const tracks = await this.getAlbumTracks(spotifyClient, album.spotifyId);

    if (tracks.length === 0) {
      logger.warn('Album has no tracks', { userId, albumId: album.spotifyId });
      return null;
    }

    const trackUris = tracks.map((track) => track.uri);

    return this.upsertSpotifyPlaylist(
      userId,
      spotifyUserId,
      spotifyClient,
      trackUris,
      {
        name: this.generatePlaylistName(album.name, artists),
        description: 'Auto-generated by DailySpin - Your album of the day',
        type: 'album_of_the_day',
      },
    );
  }

  private async getAlbumTracks(
    spotifyClient: SpotifyApi,
    albumSpotifyId: string,
  ): Promise<{ uri: string }[]> {
    logger.debug('Fetching album tracks', { albumSpotifyId });

    const albumTracks = await spotifyClient.albums.tracks(albumSpotifyId);

    return albumTracks.items.map((track) => ({ uri: track.uri }));
  }

  private generatePlaylistName(
    albumName: string,
    artists: { name: string }[],
  ): string {
    const artistNames = artists.map((a) => a.name).join(', ');
    return `DailySpin: ${albumName} - ${artistNames}`;
  }
}
