/// <reference lib="webworker" />

import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkOnly } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

const OFFLINE_PAGE = '/offline.html';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Navigation requests: try network, fall back to offline page if offline
// This lets Nuxt SSR handle redirects while still providing offline support
const navigationRoute = new NavigationRoute(
  new NetworkOnly({
    plugins: [
      {
        handlerDidError: async () => {
          return caches.match(OFFLINE_PAGE) || Response.error();
        },
      },
    ],
  }),
  {
    denylist: [/^\/api\//],
  },
);
registerRoute(navigationRoute);

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  }),
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  }),
);

// Cache Spotify album images
registerRoute(
  /^https:\/\/i\.scdn\.co\/.*/i,
  new CacheFirst({
    cacheName: 'spotify-images-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  }),
);

// Push notification types
type PushNotificationData = {
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  data?: {
    type: string;
    url?: string;
  };
  actions?: Array<{
    action: string;
    title: string;
  }>;
};

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return;

  const payload: PushNotificationData = event.data.json();

  const options = {
    body: payload.body,
    icon: payload.icon || '/icons/pwa-192x192.png',
    badge: payload.badge || '/icons/pwa-192x192.png',
    data: payload.data,
    actions: payload.actions,
  };

  event.waitUntil(self.registration.showNotification(payload.title, options));
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const data = event.notification.data as PushNotificationData['data'];
  let targetUrl = '/';

  // Determine URL based on action or notification data
  if (event.action) {
    // Handle specific actions
    switch (event.action) {
      case 'reauth':
        targetUrl = '/';
        break;
      case 'view':
        targetUrl = data?.url || '/';
        break;
      default:
        targetUrl = data?.url || '/';
    }
  } else if (data?.url) {
    targetUrl = data.url;
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList) => {
      // Check if there's already a window open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(targetUrl);
          return client.focus();
        }
      }
      // Open a new window if none exists
      return self.clients.openWindow(targetUrl);
    }),
  );
});
